version: "3.8"

services:
  shard1Srv1:
    container_name: "shard1SRV1"
    image: "mongo:latest"
    deploy:
      replicas: 1
    command: mongod --shardsvr --replSet shard1repset --port 27017 --dbpath /data/db
    ports:
      - "50001:27017"
    networks:
      - "my_overlay1"
  
  shard1Srv2:
    container_name: "shard1SRV2"
    image: "mongo:latest"
    deploy:
      replicas: 1
    command: mongod --shardsvr --replSet shard1repset --port 27017 --dbpath /data/db
    ports:
      - "50002:27017"
    networks:
      - "my_overlay1"

  shard1Srv3:
    container_name: "shard1SRV3"
    image: "mongo:latest"
    deploy:
      replicas: 1
    command: mongod --shardsvr --replSet shard1repset --port 27017 --dbpath /data/db
    ports:
      - "50003:27017"
    networks:
      - "my_overlay1"

