version: '3.8'

services:

  metasrv1:
    container_name: "metaSRV1"
    image: "mongo:latest"
    deploy:
      replicas: 1
    command: mongod --configsvr --replSet cfgrs --port 27017 --dbpath /data/db
    volumes:
      - ./metasrv1DB:/data/db/
    ports:
      - "40001:27017"
    networks:
      - "my_overlay1"

  metasrv2:
    container_name: "metaSRV2"
    image: "mongo:latest"
    deploy:
      replicas: 1
    command: mongod --configsvr --replSet cfgrs --port 27017 --dbpath /data/db
    volumes:
      - ./metasrv2DB:/data/db/
    ports:
      - "40002:27017"
    networks:
      - "my_overlay1"

  metasrv3:
    container_name: "metaSRV3"
    image: "mongo:latest"
    volumes:
      - ./metasrv3DB:/data/db/
    deploy:
      replicas: 1
    command: mongod --configsvr --replSet cfgrs --port 27017 --dbpath /data/db
    ports:
      - "40003:27017"
    networks:
      - "my_overlay1"

networks:
  my_overlay1:
    driver: overlay
